set(COMPILER_FLAGS "")

set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wall")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wextra")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Werror")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -pedantic")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wuninitialized")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wunused-parameter")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wunused-but-set-parameter")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wmissing-field-initializers")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wignored-qualifiers")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wtype-limits")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wclobbered")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wstrict-aliasing")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wimplicit-fallthrough")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wmisleading-indentation")


set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wcast-align")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wcast-qual")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wctor-dtor-privacy")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wdisabled-optimization")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wformat=2")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Winit-self")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wlogical-op")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wmissing-include-dirs")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wnoexcept")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wold-style-cast")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Woverloaded-virtual")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wredundant-decls")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wshadow")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wsign-promo")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wstrict-null-sentinel")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wstrict-overflow=5")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wundef")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wno-unused")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wno-variadic-macros")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wno-parentheses")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -fdiagnostics-show-option")
set(COMPILER_FLAGS "${COMPILER_FLAGS} -Wconversion")

#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${COMPILER_FLAGS}")
#target_compile_options(my_library PRIVATE -Werror -Wall -Wextra)